equipments_catalogue/urls.py
from django.urls import path
from . import views

app_name = 'equipments_catalogue'

urlpatterns = [
    #path('equipment_list/', views.EquipmentListView.as_view(), name='equipment_list'),
    path('equipment_categories/', views.EquipmentCategoryView.as_view(), name='equipment_categories'),
    path('equipment_by_category/<str:cats>/', views.EquipmentListByCategory, name='equipment_by_category'),
    path('equipment/<slug>/', views.EquipmentDetailView.as_view(), name='equipment_detail'),
    path('list-gear/', views.ListGearView.as_view(), name='list_gear'),
    path('search-results/', views.EquipmentListView.as_view(), name='search-results'),

]

justproduceit_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # for new authentication system
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')), # For social_django urls
    path('learn/', include('learn.urls')),
    path('students/', include('students.urls')),
    path('students/', include('django.contrib.auth.urls')),

    # path('accounts/', include('allauth.urls')),
    path('equipments/', include('equipments_catalogue.urls', namespace='equipments_catalogue')),
    path('', include('pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learn/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.CourseListView.as_view(), name='course_list'),
    path('mine/', views.ManageCourseListView.as_view(), name='manage_course_list'),
    path('create/', views.CourseCreateView.as_view(), name='course_create'),
    path('<pk>/edit/', views.CourseUpdateView.as_view(), name='course_edit'),
    path('<pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),
    path('<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('module/<int:module_id>/content/<model_name>/create/', views.ContentCreateUpdateView.as_view(), name='module_content_create'),
    path('module/<int:module_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(), name='module_content_update'),
    path('content/<int:id>/delete/', views.ContentDeleteView.as_view(), name='module_content_delete'),
    path('module/<int:module_id>/', views.ModuleContentListView.as_view(), name='module_content_list'),
    path('module/order/', views.ModuleOrderView.as_view(), name='module_order'),
    path('content/order/', views.ContentOrderView.as_view(), name='content_order'),
    path('category/<slug:category>/', views.CourseListView.as_view(), name='course_list_category'),
    path('<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail'),

]

learn/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from .fields import OrderField
from django.template.loader import render_to_string
from django.conf import settings

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class Course(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='courses_created', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='courses', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    students = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='courses_joined', blank=True)
    price = models.PositiveIntegerField()
    
    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

class Module(models.Model):
    course = models.ForeignKey(Course, related_name='modules', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=['course'])
    
    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'{self.order}. {self.title}'

   

class Content(models.Model):
    module = models.ForeignKey(Module, related_name='contents', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, limit_choices_to={'model__in': ('text', 'video', 'image', 'file')})
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['module'])

    class Meta:
        ordering = ['order']

class ItemBase(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, 
                                    related_name='%(class)s_related',
                                    on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title
    
    def render(self):
        return render_to_string(f'learn/content/{self._meta.model_name}.html', {'item': self})


class Text(ItemBase):
    content = models.TextField()

class File(ItemBase):
    file = models.FileField(upload_to='files')

class Image(ItemBase):
    file = models.FileField(upload_to='images')

class Video(ItemBase):
    url = models.URLField()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}JustProduceit{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}

    <title>{% block title %}JustProduceit{% endblock title %}</title>
    <!--Main css-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

    <!-- Owl Stylesheets -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

    <!-- Flex slider-->
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />
 
    <!-- javascript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.js' %}"></script>


    <meta name="title" content="JustProduceit">
    <meta name="keywords" content="justProduceit, rent video equipments in lagos, rent video equipments, just produce it, produce it, just, rent camera, rent videocamera">
    <meta name="description" content="Learn essential skills from Africa's best creators and rent top gear from the best production companies and owners near you.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'img/favicon.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon.png' %}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://justproduce.it/">
    <meta property="og:title" content="JustProduceit">
    <meta property="og:image" content="https://justproduce.it/img/justproduceit.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://justproduce.it/">
    <meta property="twitter:title" content="JustProduceit">
    <meta property="twitter:description" content="Learn essential skills from Africa's best creators and rent top gear from the best production companies and owners near you.">
    <meta property="twitter:image" content="https://justproduce.it/img/justproduceit.png">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-180296503-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-180296503-1');
    </script>
  </head>

  <body>
    <header>
      <nav class="navbar">
        <div>
          <div class="row justify-content-between align-items-center">
            <div class="logo pd">
              <a href="/" class="brand-name">
                <img class="logo-img" src="{% static 'img/just-beta-logo.png' %}" alt="Just Produce it logo">
              </a>
            </div>
            <button class="navbar-nav-toggle pd">
              <span></span>
            </button>
            <div class="navbar-nav">
              <ul>
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'equipments_catalogue:equipment_categories' %}">Rent</a></li>            
                <li><a href="{% url 'equipments_catalogue:list_gear' %}">Learn</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                {% if user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="sub-menu-toggle">{{ user.first_name }}</a>
                  <ul class="sub-menu">
                    <li><a href="{% url 'password_reset' %}">Reset Password</a></li>
                    <li><a href="{% url 'password_change' %}">Change Password</a></li>
                    <!-- <li><a href="{% url 'student_course_list' %}">View My Courses</a></li> -->
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                  </ul>
                </li>
                {% else %}
                  <li><a  href="{% url 'login' %}">Login</a></li>
                  <li><a class="btn-dark"href="{% url 'student_registration' %}">Sign Up</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </header>
    {% block content %}
      
    {% endblock  %}
    <!-- For new stuffs -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script>
      $(document).ready(function() {
        {% block domready %}
        {% endblock %}
      });
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

  </body>


{% include 'footer.html' %}

<script type="text/javascript">
  $(function(){
    SyntaxHighlighter.all();
  });
  $(window).load(function(){
    $('.flexslider').flexslider({
      animation: "slide",
      controlNav: "thumbnails",
      start: function(slider){
        $('body').removeClass('loading');
      }
    });
  });
</script>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
    <h1>Welcome to JPI Contact Page</h1>
{% endblock %}

templates/equipment_by_category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
    <!-- {% if equipment_category %}
        <h1>Welcome to JPI {{ cats }} Page</h1>
        {% for equipment in equipment_category %}
            <div>
                <div class="explore-courses-box">
                    <a href="{% url 'equipments_catalogue:equipment_detail' equipment.slug %}">
                        <img src="{{ equipment.image.url }}" alt="image of equipment">
                    </a>
                    <div class="courses-box-deets">
                    <h3>{{ equipment.name }}</h3>
                    <p>{{ equipment.seller_name }}</p>
                    <p class="price">₦ {{ equipment.price }}</p>
                    </div>
                </div>
                {{ equipment.image }}
            </div>
            <br>
        {% endfor %}
    {% else %}
    <h1>Sorry this page does not exist </h1>
    {% endif %} -->


    <section id="search">
        <div class="search">
        
        </div>
      </section>
        <section id="default" class="hero-shop">
              <div class="default">
                <div class="hero-deets">
                  <h1>The largest gear sharing community</h1>
                  <p>your place to discover top gear</p>
      
                </div>
              </div>
          </section>
      
          
          <section id="shop-list">
            <div class="shop-list row">
              <div class="shop-list-que">
                <aside>
                  <div class="sidebar">
                    
      
                    <div class="single-category">
                      <div class="search-class">
            <h4>Search <span class="oop">Here</span></h4>
            <form action="{% url 'equipments_catalogue:search-results' %}" method="get" class="search-transform">
              
              <input class="form-control" type="search" name="q" placeholder="Search here..." required>
              <button class="btn-search"><span class="search-icon">&#128269</span></button>
            </form>
          </div>
                        <h4>Product <span class="oop">Categories</span> </h4>

                        
                            <ul class="list-group">
                            {% for category in categories %}    
                                <li class="list-group-item">
                                    <a href="{% url 'equipments_catalogue:equipment_by_category' category.name %}" class="selected-cat">{{ category.name }}</a> 
                                    <!-- <span class="badge pills">{{ equipments | length }}</span> -->
                                </li>
                            {% endfor %}   
                            </ul>


                    </div>
      
                    <div class="single-filter">
      
                    </div>
      
                  </div>
                </aside>
              </div>
      
              <div class="shop-list-options">
                <div class="list-options-top">
                  <div class="list-result">
                    <h4>Showing all {{ equipment_category | length }} results</h4>
                  </div>
                  <!-- <div class="list-ordering">
                    <div class="list-ordering-select">
                      <select>
                      <option value="menu_order" selected="selected">Default Sorting</option>
                                                      <option value="popularity">Sort by Popularity</option>
                                                      <option value="rating">Sort by Average rating</option>
                                                      <option value="date">Sort by latest</option>
                                                      <option value="price">Sort by Price: low to high</option>
                                                      <option value="price-desc">Sort by Price: high to low</option>
                      </select>
                    </div>
                  </div> -->
      <!-- grid  -->
                    <div class="product-grid">


            {% for equipment in equipment_category %}
              <div class="product-grid-box">
                  <a href="{% url 'equipments_catalogue:equipment_detail' equipment.slug %}">
                      <div class="product-image">
                          <img src="{{ equipment.image_1.url }}" alt="Image of equipment">
                      </div>
                          <div class="product-content">
                          <h3 class="title">{{ equipment.name }}</h3>
                          <p>{{ equipment.vendor_name }}</p>
                          <span>&#8358; {{ equipment.price }}</span>
                      </div>
                  </a>
              </div>
            {% empty %}
              <h4>Sorry, no items at the moment.</h4>
            {% endfor %}
      
                     
                </div>
              </div>
      
            </div>
          </section>
      





{% endblock %}

templates/equipment_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<section id="single-page">
<div class="single-page">
  <div class="single-page-deets">
      <div class="product-img">
      <section class="slider">
        <div class="flexslider">
          <ul class="slides">
            {% if equipment.image_1 %}
            <li data-thumb="{{ equipment.image_1.url }}">
              <img src="{{ equipment.image_1.url }}" />
            </li>
            {% else %}

            {% endif %}

            {% if equipment.image_2 %}
            <li data-thumb="{{ equipment.image_2.url }}">
              <img src="{{ equipment.image_2.url }}"/>
            </li>
            {% else %}

            {% endif %}
            {% if equipment.image_3 %}
            <li data-thumb="{{ equipment.image_3.url }}">
              <img src="{{ equipment.image_3.url }}" />
            </li>
            {% else %}
            {% endif %}

            {% if equipment.image_4 %}
            <li data-thumb="{{ equipment.image_4.url }}">
              <img src="{{ equipment.image_4.url }}" />
            </li>
            {% else %}

            {% endif %}
          </ul>
        </div>
        
      </section>
      <hr>
      <div class="product-info">
        <div class="product-name">
          <div class="cat">
          <p>{{ object.get_category_display }}</p>
          </div>
          <h2>{{ object.name }}</h2>
          <div class="location">
            <img src="{% static 'img/location-pin.svg' %}" alt="location icon">
            <p>{{ object.vendor_location }}</p>
          </div>
        </div>
      </div>
      <hr>
        <div class="product-info">
          <h4>Description</h4>
          {{ object.description }}
        </div>
      </div>

    <div class="product-deets">
    
      <div class="product-price">
        <p>₦{{ object.price }}</p>
      </div>
    
      <br>
      <div class="rent-profile">
       <h4>Get in touch</h4>
        <img src="{% static 'img/profile.svg' %}" alt="">
        <p><b>{{ object.vendor_name }}</b></p>
      </div>
      <div class="get-in-touch">
        {% if object.vendor_number %}
        <a href="tel:{{ object.vendor_number }}" class="call-btn"> <img src="{% static 'img/call.svg' %}" alt="call icon">{{ object.vendor_number }}</a>
        {% else %}

        {% endif %}
        <br>
        <br>
        <br>
        {% if object.vendor_number_2 %}
        <a href="tel:{{ object.vendor_number_2 }}" class="call-btn"> <img src="{% static 'img/call.svg' %}" alt="call icon">{{ object.vendor_number_2 }}</a>

        {% else %}

        {% endif %}

      </div>
    </div>
  </div>
</div>
</section>

 <script type="text/javascript">
  $(function(){
    SyntaxHighlighter.all();
  });
  $(window).load(function(){
    $('.flexslider').flexslider({
      animation: "slide",
      controlNav: "thumbnails",
      start: function(slider){
        $('body').removeClass('loading');
      }
    });
  });
</script>




{% comment %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ equipment.pic.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="{% url 'equipments_catalogue:equipment_categories' %}">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>#{{ object.price }}</del>
              </span>
              <span>#{{ object.discount_price }}</span>
              {% else %}
              <span>#{{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

           <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> 
            <br/>
            <p>Get in touch with {{ object.seller }}</p>&middot;
            <p>{{ object.seller_number }}</p>
            <!-- Pay and cart buttons-->
            <!-- <a href="/fire-equipment-payment/{{equipment.id}}/" class="btn btn-md my-0 p" style="background-color:#22dd22;">Pay</a>

            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a> -->

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <!-- <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div> -->
        <!--Grid column-->

      </div>

    </div>
  </main>
{% endcomment %}
  <!-- SCRIPTS -->
  </body>




{% endblock %}

templates/equipment_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
<section id="default" class="hero-shop">
    <div class="default">
      <div class="hero-deets">
        <h1>The largest gear sharing community</h1>
        <p>your place to discover top gear</p>

      </div>
    </div>
</section>
    <!-- {% for equipment in object_list %}
        {{ equipment.name }} in {{ equipment.category }}<br><br>
    {% endfor %} -->
    
    <div class="shop-list-options">
        <div class="list-options-top">
    {% for equipment in object_list %}
    
    
            <div class="product-grid-box">
                <a href="{% url 'equipments_catalogue:equipment_detail' equipment.slug %}">
                    <div class="product-image">
                        <img src="{{ equipment.image_1.url }}" alt="Image of equipment">
                    </div>
                        <div class="product-content">
                        <h3 class="title">{{ equipment.name }}</h3>
                        <p>{{ equipment.vendor_name }}</p>
                        <span>&#8358; {{ equipment.price }}</span>
                    </div>
                </a>
            </div>
     
    {% empty %}
        <h4>Sorry, no items at the moment.</h4>

        <!-- <a href="{% url 'equipments_catalogue:equipment_detail' equipment.slug %}">{{ equipment.name }}</a><br><br> -->
    {% endfor %}
   </div>
    </div>
{% endblock %}

templates/feedback.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Start a project{% endblock %}

{% block content %}
<iframe
              src="https://justproduceit.wispform.com/d1e21cb5"
              frameborder="0"
              marginheight="0"
              marginwidth="0"
              style="height:100vh; width:100vw">
                Loading...
            </iframe>
{% endblock %}

templates/footer.html
{% load static %}
<footer>
    <div class="footer">
      <div class="footer-info">

        <div class="footer-img">
          <img src="{% static 'img/just-beta-logo.png' %}" alt="footer logo">
        </div>
        
        <div class="footer-deets">
          <div class="footer-box flex">
            <h3>Contact us</h3>
            <ul>
              <li><a href="https://goo.gl/maps/" target="_blank"> Lagos Nigeria</a> </li>
              <li><a href="mailto:hello@justproduceit.com" > Email Us</a> </li>
            </ul>
            </div>

          <div class="footer-box flex">
            <h3> Useful LInks</h3>
            <ul>
              <li><a href="/">Home</a></li>                
              <li><a href="{% url 'equipments_catalogue:equipment_categories' %}">Rent</a></li>
              <li><a href="{% url 'equipments_catalogue:equipment_categories' %}">Categories</a></li>
              <li><a href="{% url 'equipments_catalogue:list_gear' %}">Learn</a></li>
              <li><a href="{% url 'about' %}">About</a></li>

            </ul>
          </div>

          <div class="footer-box flex">
            <h3> Discover</h3>
            <ul>
              <li><a href="{% url 'equipments_catalogue:list_gear' %}">Create</a></li>                
              <!-- <li><a href="gear">Gear</a></li> -->
              <li><a href="{% url 'privacy-policy' %}">Privacy Policy</a></li>
            </ul>
            
          </div>
     
      </div>

      </div>
    </div>
    <div class="copyright">
      <p>Copyright Global Creative Operations 2020- All Rights Reserved</p>
    </div>
  </footer>
  <div class="feedback" id="fixedbutton">
    <a href="{% url 'feedback' %}" class="btn-dark">Open Beta</a>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script src="{% static 'js/owl.carousel.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
  <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>

  </body>

templates/learn-coming-soon.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section id="default" class="hero-learn">
    <div class="default">
      <div class="hero-deets">
      <h1>Coming Soon</h1>
        <!-- <h1>Learn anytime</h1>
        <p>become the best version of you today.</p> -->
      </div>
    </div>
</section>


<!-- <section id="tutor">
  <div class="tutor">
    <div class="tutor-info">
      <div class="tutor-img">
        <img src="img/learn-tutor.png" alt="">
      </div>

      <div class="tutor-deets">
        <h2>Learn Videography</h2>
        <br>
        <p>We’re a team of makers, thinkers, explorers and 
          theatre singers. We approach work and play with curiosity
           and experimentation, using what we learn to create meaningful 
           digital products that connect with people, just like you.
        </p>
        <br>
        <a href="" class="btn-red">View Course</a>
      </div>
    </div>
  </div>
</section> -->


{% endblock %}

templates/list-gear.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section id="default" class="hero-list-gear">
    <div class="default">
      <div class="hero-deets">
      <h1>Coming Soon</h1>
        <!-- <h1>Learn anytime</h1>
        <p>become the best version of you today.</p> -->
      </div>
    </div>
  </section>


    <!-- <section id="tutor">
      <div class="tutor">
        <div class="tutor-info">
          <div class="tutor-img">
            <img src="img/learn-tutor.png" alt="">
          </div>

          <div class="tutor-deets">
            <h2>Learn Videography</h2>
            <br>
            <p>We’re a team of makers, thinkers, explorers and 
              theatre singers. We approach work and play with curiosity
               and experimentation, using what we learn to create meaningful 
               digital products that connect with people, just like you.
            </p>
            <br>
            <a href="" class="btn-red">View Course</a>
          </div>
        </div>
      </div>
    </section> -->

{% endblock %}

templates/registration_email.html
{% load static %}

Hi, {{ name }}.

I'm Laide and I may or may not be a robot, but that's not the point.

The real story here is that you are special because you're among the first set of people experiencing Justproduce.it.

I know it can be difficult to create content, access vendors, and organize creative projects in our Landscape and Justproduce.it is here to help with that.

Here are a few things you can do with the Beta version right now.

You can also access a free inventory of production equipment, studio spaces, locations, and production support from vendors around your location.

If you're looking for a seamless production experience, Justproduce.it can hook you up with a production team from one of our trusted and verified partners, monitoring the process from start to finish with our automated systems.

We'll be rolling out a few more features as we go on this journey together, so be rest assured all your production challenges will be considered!

Now, because you're so special, we'll be relying on your feedback to make this work perfectly for you.

Feel free to use the OpenBeta button on the platform to leave your feedback and help us serve you better! 

Speak soon - L

templates/start_a_project.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Start a project{% endblock %}

{% block content %}
<iframe src="https://justproduceit.wispform.com/7a88a30b" 
    frameborder="0" marginheight="0" 
    marginwidth="0" style="height:100vh; width:100vw">Loading...
</iframe>
{% endblock %}

templates/start_another_project.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Start a project{% endblock %}

{% block content %}
<iframe src="https://justproduceit.wispform.com/7a88a30b" 
    frameborder="0" marginheight="0" 
    marginwidth="0" style="height:100vh; width:100vw">Loading...
</iframe>
{% endblock %}